### ISSUE TITLE
More links for SISR task

### ISSUE THREAD

**Issue by neosr-project** [lixinustc/Awesome-diffusion-model-for-image-processing#1]
Thanks for this list. Here's some other links to recent diffusion-based single-image super-resolution projects:
- [ResShift](https://github.com/zsyOAOA/ResShift)
- [PartDiff](https://arxiv.org/abs/2307.11926)
- [DiWa](https://github.com/brian-moser/diwa)
- [YODA](https://arxiv.org/pdf/2308.07977v1.pdf)

There's also [GigaGAN](https://mingukkang.github.io/GigaGAN/), but nobody has replicated their results.

**Comment by lixinustc** [comment]
We really appreciate your lists, which will further improve our summary. We will incorporate it into our repository.
