### ISSUE TITLE
Update on Diffusion model-based Image/Video Compression

### ISSUE THREAD

**Issue by tongdaxu** [lixinustc/Awesome-diffusion-model-for-image-processing#7]
Hi,

Thanks for this cool work. Would you mind appending our work on diffusion image codec?

idempotence and perceptual image compression, ICLR 2024
Arxiv: https://arxiv.org/abs/2401.08920
Code: https://github.com/tongdaxu/idempotence-and-perceptual-image-compression

Besides, [TOWARDS IMAGE COMPRESSION WITH PERFECT REALISM AT ULTRA-LOW BITRATES](https://arxiv.org/abs/2310.10325) is also accepted by ICLR 2024.

A typo, [Lossy Image Compression with Conditional Diffusion Models](https://arxiv.org/abs/2209.06950) is presented in ICML 2023 workshop and accepted in NeurIPS 2024, not ICLR 2023. [Text + Sketch: Image Compression at Ultra Low Rates](https://arxiv.org/abs/2307.01944) is also presented in ICML 2023 workshop.

@lixinustc

**Comment by lixinustc** [comment]
Thanks for your very excellent works, we will incorporate these works into our repo, and revise the corresponding parts.

**Comment by tongdaxu** [comment]
> Thanks for your very excellent works, we will incorporate these works into our repo, and revise the corresponding parts.

Thanks for including this, some bug fixs:
* [Lossy Image Compression with Conditional Diffusion Models](https://arxiv.org/abs/2209.06950) is published in NeurIPS 2023, not NeurIPS 2024 (I made a mistake, sorry!). The code is also released in https://github.com/buggyyang/cdc_compression
* [Idempotence and Perceptual Image Compression](https://arxiv.org/abs/2401.08920) is already published in ICLR 2024.

Thanks for your time

@lixinustc

**Comment by lixinustc** [comment]
Thanks for your reminding. I will incorporate it into this repo.
